apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-template
spec:
  entrypoint: whalesay-template
  templates:
    - name: whalesay-template
      inputs:
        artifacts:
          - name: input-data
            path: /tmp/input-file
      outputs:
        artifacts:
          - name: output-file
            path: /tmp/output-file.txt
      container:
        image: docker/whalesay
        command: [ sh, -c ]
        args: ["ls -lh /tmp/input-file >> /tmp/output-file.txt"]
