apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-consumer-wft-
spec:
  arguments:
    parameters:
      - name: source-path
        value: lorem.txt # The specific key for the S3 input object
      - name: target-path
        value: result.txt # The specific key where the S3 output object will be written
    artifacts:
      - name: input-file
        s3:
          bucket: test
          insecure: true
          endpoint: l-k8s01-master.spb.spacebel.be:30901
          accessKeySecret:
            name: minio-credentials
            key: accessKey
          secretKeySecret:
            name: minio-credentials
            key: secretKey
          key: "{{inputs.parameters.source-path}}"
  # Reference the WorkflowTemplate
  workflowTemplateRef:
    name: artifact-consumer-wft
