apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-consumer-wft-
spec:
  arguments:
    parameters:
      - name: target-path
        value: result.png # The specific key where the S3 output object will be written
    artifacts:
      - name: input-file
        http:
          url: https://en.wikipedia.org/static/images/icons/wikipedia.png
  # Reference the WorkflowTemplate
  workflowTemplateRef:
    name: artifact-consumer-wft
