workflow:
  serviceAccount:
    create: true
    name: "executor"
  rbac:
    create: true
artifactRepositoryRef:
  artifact-repositories:
    annotations:
      workflows.argoproj.io/default-artifact-repository: default-artifact-repository
    default-artifact-repository:
      s3:
        bucket: test
        endpoint: 172.17.20.10:30901
        insecure: false
        caSecret:
          name: minio-cert
          key: minio.pem
        accessKeySecret:
         name: minio-credentials
         key: accessKey
        secretKeySecret:
         name: minio-credentials
         key: secretKey