apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-consumer-wft-2-
spec:
  arguments:
    parameters:
      - name: source-path
        value: lorem.txt # The specific key for the S3 input object
      - name: target-path
        value: result.txt # The specific key where the S3 output object will be written
    artifacts:
      - name: input-file
        s3:
          bucket: test
          key: "{{inputs.parameters.source-path}}"
  # Reference the WorkflowTemplate
  workflowTemplateRef:
    name: artifact-consumer-wft-2
