apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-demo-workflow-
spec:
  entrypoint: gdal-manipulation
  templates:
    - name: gdal-manipulation
      dag:
        tasks:
          - name: gdal-translate
            templateRef:
              name: wf-template-1
              template: gdal-translate-template
            arguments:
              artifacts:
                - name: input-file
                  s3:
                    bucket: sentinel-cogs
                    insecure: true
                    #endpoint: s3-accesspoint.us-west-2.amazonaws.com
                    endpoint: s3.amazonaws.com
                    region: us-west-2
                    key: /sentinel-s2-l2a-cogs/24/W/WS/2024/5/S2B_24WWS_20240521_0_L2A
            retryStrategy:
              limit: 10
              retryPolicy: "Always"
          - name: gdal-info
            dependencies: [gdal-translate]
            templateRef:
              name: wf-template-2
              template: gdal-info-template
            arguments:
              artifacts:
                - name: input-file
                  from: "{{tasks.['gdal-translate'].outputs.artifacts.['processed-dataset']}}"
      outputs:
        artifacts:
          - name: gdal-report
            from: "{{tasks.['gdal-info'].outputs.artifacts.report}}"
          - name: processed-image
            from: "{{tasks.['gdal-translate'].outputs.artifacts.['processed-dataset']}}"