apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dag-template
spec:
  entrypoint: gdal-manipulation
  nodeSelector:
    accelerator: "example-gpu"
  templates:
    - name: gdal-manipulation
      podSpecPatch: '{"containers":[{"name":"main", "resources":{"requests":{"memory": "100M" }}}]}'
      retryStrategy:
        limit: "10"
      inputs:
        parameters:
          - name: image-url
      dag:
        tasks:
          - name: gdal-translate
            templateRef:
              name: gdal-translate-template
              template: gdal-translate
            arguments:
              artifacts:
                - name: input-dataset
                  http:
                    url: "{{inputs.parameters.image-url}}"
          - name: gdal-info
            dependencies: [gdal-translate]
            templateRef:
              name: gdal-info-template
              template: gdal-info
            arguments:
              artifacts:
                - name: input-dataset
                  from: "{{tasks.gdal-translate.outputs.artifacts.processed-dataset}}"
          - name: stage-out
            dependencies: [gdal-info]
            template: stage-out
            arguments:
              artifacts:
                - name: artifact-to-export
                  from: "{{tasks.gdal-translate.outputs.artifacts.processed-dataset}}"
#      outputs:
#        artifacts:
#          - name: processed-image
#            from: "{{tasks.gdal-translate.outputs.artifacts.processed-dataset}}"
#            s3:
#              bucket: test
#              key: result-2.tif
    - name: stage-out
      inputs:
        artifacts:
          - name: artifact-to-export
            path: /outputs
      outputs:
        artifacts:
          - name: processed-image
            path: /outputs
            s3:
              bucket: outputs
              key: result.tif
              insecure: true
              endpoint: l-k8s01-master.spb.spacebel.be:30901
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
           # from: "{{tasks.gdal-translate.outputs.artifacts.processed-dataset}}"
      container:
        image: ghcr.io/osgeo/gdal:alpine-small-latest
        command: [ sh, -c ]
        args: [ "ls -la /outputs" ]