apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: gdal-translate-template
spec:
  entrypoint: gdal-translate
  templates:
    - name: gdal-translate
      inputs:
        artifacts:
          - name: input-dataset
            path: /tmp/input-file.tif
      outputs:
        artifacts:
          - name: processed-dataset
            path: /tmp/processed-file.tif
      container:
        image: ghcr.io/osgeo/gdal:alpine-small-latest
        command: [sh, -c]
        args: ["gdal_translate -mo \"project=dimsum\" /tmp/input-file.tif /tmp/processed-file.tif"]