apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: stage-out-template
spec:
  entrypoint: stage-out
  templates:
    - name: stage-out
      inputs:
        parameters:
          - name: export-key
        artifacts:
          - name: artifact-to-export
            path: /outputs
      outputs:
        artifacts:
          - name: result
            path: /outputs
            s3:
              bucket: archive
              key: "{{inputs.parameters.export-key}}"
              insecure: true
              endpoint: l-k8s01-master.spb.spacebel.be:30901
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
          # from: "{{tasks.gdal-translate.outputs.artifacts.processed-dataset}}"
      container:
        image: ghcr.io/osgeo/gdal:alpine-small-latest
        command: [ sh, -c ]
        args: [ "ls -la /outputs" ]