apiVersion: v1
kind: Service
metadata:
  name: argo-custom-service
spec:
  type: NodePort
  selector:
    app: argo-server
  ports:
    - protocol: TCP
      port: 2746
      targetPort: 2746
      nodePort: 32747
