name: Deploy Argo Workflows MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install PDM
        run: python -m pip install pdm

      - name: Install dependencies with PDM
        run: pdm install

      - name: Build MkDocs site
        run: pdm run mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTION_DEPLOY_KEY }}
          publish_dir: ./site
